# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Desktop/Arty-S7-50-Master.xdc

# Block Designs: bd/design_2/design_2.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2 || ORIG_REF_NAME==design_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_proc_sys_reset_0_0/design_2_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_proc_sys_reset_0_0 || ORIG_REF_NAME==design_2_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_clk_wiz_0_2/design_2_clk_wiz_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_clk_wiz_0_2 || ORIG_REF_NAME==design_2_clk_wiz_0_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axi_uartlite_0_0/design_2_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_axi_uartlite_0_0 || ORIG_REF_NAME==design_2_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_microblaze_0_axi_periph_1/design_2_microblaze_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_microblaze_0_axi_periph_1 || ORIG_REF_NAME==design_2_microblaze_0_axi_periph_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axi_gpio_1_0/design_2_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_axi_gpio_1_0 || ORIG_REF_NAME==design_2_axi_gpio_1_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_xbar_0/design_2_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_xbar_0 || ORIG_REF_NAME==design_2_xbar_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Arty_RGB_AXI_0_0/design_2_Arty_RGB_AXI_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_Arty_RGB_AXI_0_0 || ORIG_REF_NAME==design_2_Arty_RGB_AXI_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axi_gpio_0_0/design_2_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_axi_gpio_0_0 || ORIG_REF_NAME==design_2_axi_gpio_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_mdm_1_1/design_2_mdm_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_mdm_1_1 || ORIG_REF_NAME==design_2_mdm_1_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_microblaze_0_2/design_2_microblaze_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_microblaze_0_2 || ORIG_REF_NAME==design_2_microblaze_0_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_dlmb_v10_2/design_2_dlmb_v10_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_dlmb_v10_2 || ORIG_REF_NAME==design_2_dlmb_v10_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_ilmb_v10_2/design_2_ilmb_v10_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_ilmb_v10_2 || ORIG_REF_NAME==design_2_ilmb_v10_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_dlmb_bram_if_cntlr_2/design_2_dlmb_bram_if_cntlr_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_dlmb_bram_if_cntlr_2 || ORIG_REF_NAME==design_2_dlmb_bram_if_cntlr_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_ilmb_bram_if_cntlr_2/design_2_ilmb_bram_if_cntlr_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_ilmb_bram_if_cntlr_2 || ORIG_REF_NAME==design_2_ilmb_bram_if_cntlr_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_lmb_bram_2/design_2_lmb_bram_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_lmb_bram_2 || ORIG_REF_NAME==design_2_lmb_bram_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_mig_7series_0_0/design_2_mig_7series_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_mig_7series_0_0 || ORIG_REF_NAME==design_2_mig_7series_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_rst_mig_7series_0_81M_0/design_2_rst_mig_7series_0_81M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_rst_mig_7series_0_81M_0 || ORIG_REF_NAME==design_2_rst_mig_7series_0_81M_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_auto_pc_0/design_2_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_auto_pc_0 || ORIG_REF_NAME==design_2_auto_pc_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_auto_us_0/design_2_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_auto_us_0 || ORIG_REF_NAME==design_2_auto_us_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_auto_cc_0/design_2_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_auto_cc_0 || ORIG_REF_NAME==design_2_auto_cc_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_auto_ds_3/design_2_auto_ds_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_auto_ds_3 || ORIG_REF_NAME==design_2_auto_ds_3} -quiet] -quiet

# IP: bd/design_2/ip/design_2_auto_ds_2/design_2_auto_ds_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_auto_ds_2 || ORIG_REF_NAME==design_2_auto_ds_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_auto_ds_1/design_2_auto_ds_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_auto_ds_1 || ORIG_REF_NAME==design_2_auto_ds_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_auto_ds_0/design_2_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_auto_ds_0 || ORIG_REF_NAME==design_2_auto_ds_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_auto_us_1/design_2_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_auto_us_1 || ORIG_REF_NAME==design_2_auto_us_1} -quiet] -quiet

# XDC: bd/design_2/design_2_ooc.xdc
